### PR TITLE
Test export draft

### PR DESCRIPTION
**Pull request by avdata99**
Related to [Multi#527](https://github.com/GSA/datagov-ckan-multi/issues/527)

This PR:
 - Adds a [test case](https://github.com/GSA/ckanext-datajson/blob/test_urls/ckanext/datajson/test-inventory/test_export.py#L33) for draft.json `/organization/{org.id}/draft.json`
 - Adds a new test environment for Inventory-next (with CKAN 2.8)
 -  Divide test for catalog vs Inventory (catalog uses harvest, Inventory just used to expose URLs)

### Notes

DataJSON is used in different ways in Catalog and Inventory apps
Catalog use it to harvest and Inventory use it to expose JSON data.

### CODE REVIEW

**Review by anuveyatsu — APPROVED** [review]
Looks good @avdata99 
Do you know if values of `publishing_status` are case sensative?

**Comment by avdata99** [comment]
> publishing_status

**Comment by avdata99** [comment]
> Looks good @avdata99
> Do you know if values of `publishing_status` are case sensative?

Yes @anuveyatsu, it's sensitive
https://github.com/GSA/ckanext-datajson/blob/test_urls/ckanext/datajson/plugin.py#L225:L249

The UI expose these options with a capital case
https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L291:L291

**Review by anuveyatsu — APPROVED** [review]
LGTM

**Review by jbrown-xentity — APPROVED** [review]
Looks good, love tests!
Is there a reason you are adding usmetadata and dcat_usmetadata to the `.ini` file, and why that would be needed for local testing? Just trying to understand the dependencies...

**Comment by avdata99** [comment]
> Looks good, love tests!
> Is there a reason you are adding usmetadata and dcat_usmetadata to the `.ini` file, and why that would be needed for local testing? Just trying to understand the dependencies...

I think USMetadata and dcat_usmetada should be included for _inventory_ tests to really cover what happened when we export this draft JSON file. The only context in which we export this data is using these extensions.

**Pull request merged**
