### PR TITLE
Fix Hard Fail Errors

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Related to
- https://github.com/GSA/data.gov/issues/3532

### CODE REVIEW

**Comment by robert-bryson** [comment]
Linting while our eyes are on it.

**Review by robert-bryson — DISMISSED** [review]

**Review by btylerburton — DISMISSED** [review]

**Comment by robert-bryson** [comment]
Also, my ide shows that everything in `gather_stage()` is unreachable after the [`return []` in the `try`/`except`](https://github.com/GSA/ckanext-datajson/blob/1906842346380c42088226cbf1bb8aefc2c27b3f/ckanext/datajson/datajson.py#L126). Are we sure this is correct?

**Comment by nickumia-reisys** [comment]
@robert-bryson Your linter broke it 😢

**Comment by nickumia-reisys** [comment]
Can I undo your linting change?

**Comment by robert-bryson** [comment]
> Can I undo your linting change?

Yeah, go ahead. I'll fix it in another PR. Sorry to drop in, break it, and get distracted by a meeting.

**Review by robert-bryson — APPROVED** [review]

**Comment by robert-bryson** [comment]
> > Can I undo your linting change?
> 
> Yeah, go ahead. I'll fix it in another PR. Sorry to drop in, break it, and get distracted by a meeting.

I deleted it and gave a fresh review. Sorry about that.

**Comment by robert-bryson** [comment]
I know it's not in scope for this work, but still think this change isn't going to affect anything. The [`try` statement](https://github.com/GSA/ckanext-datajson/blob/5a6fedfe395260d14ab47356b4632dcd0520f3c9/ckanext/datajson/datajson.py#L116) above the changes hits a function that doesn't return anything and only runs [`raise Exception("Not implemented")`](https://github.com/GSA/ckanext-datajson/blob/5a6fedfe395260d14ab47356b4632dcd0520f3c9/ckanext/datajson/datajson.py#L101).

**Comment by nickumia-reisys** [comment]
Per the logs in the issue above,
```bash
File "/usr/lib/ckan-new/src/ckanext-datajson/ckanext/datajson/datajson_ckan_28.py", line 296, in gather_stage
    get_action('package_update')(self.context(), pkg)
```

@robert-bryson Even though I understand what you're saying, It was hitting the line somehow.  And the code has been the same way since [September 2021](https://github.com/GSA/ckanext-datajson/blob/b7af305bbb93fcb30fb4c6ddf55b91ddb2455bc2/ckanext/datajson/datajson_ckan_28.py#L100-L119).

**Pull request merged**
