### PR TITLE
Updates to be more generic for other agencies

### PR DESCRIPTION
**Pull request by inghamn**
Started some work on making the code not so reliant on custom wrapper functions.  This is intended to ease adoption by other agencies using CKAN.

### CODE REVIEW

**Comment by adborden** [comment]
Hello, thank you for contributing to one of our repositories! I know this PR is over two years old, sorry there's been no response on this. Are you still interested in getting these changes in?

**Comment by inghamn** [comment]
This was a long time ago, and I'm trying to remember what I was working on.  I'm digging through my emails from that time period.

I believe these were updates to help us pass validation when publishing our data to data.gov.  We had validation problems from data.gov.

Data.gov required a dataset identifier that was a URL to the dataset, however that information was not available to ckanext-datajson, at the time.

Also, this PR includes changes intended to make it easier to specify custom field mappings to match the US Metadata specification.

This was, indeed, a long time ago.  As I review the changes, now, they seem like reasonable hooks to support future extensions and needs.

**Comment by adborden** [comment]
Thanks for digging up the background on this. Can you give an example of how these hooks are used? I wasn't aware that folks are extending functionality from this.

**Comment by inghamn** [comment]
I'm really struggling to remember stuff from that far back.  If this PR doesn't seem like a good thing to merge, that's an acceptable outcome for me, too.

There is the US Metadata CKAN extension, but I was not able to get it's output to validate with the federal government.

https://github.com/GSA/USMetadata/

I did these changes to get our instance of CKAN to publish a data.json output the passed the federal validator.  Since I've updated CKAN a few times since then, our current instance does not pass validation.

https://labs.data.gov/dashboard/validate?schema=non-federal-v1.1&output=browser&datajson_url=https%3A%2F%2Fdata.bloomington.in.gov%2Fdata.json&qa=true

I remember working to get the data.json output to include the required identifier field for each dataset.  I also worked to have the data.json include an accessURL for each dataset.  Getting the accessURL into data.json, I believe, was what prompted the functions ckan_url_for_dataset_id().

I vaguely remember having the problem that datajson was producing URLs assuming the CKAN was always installed at the root of the host, instead of allowing for subdirectories.  I also ran into problems when CKAN was hosted behind a reverse proxy.  The datajson code assumed that the host of the machine was the host to be used for URL generation.

https://data.bloomington.in.gov
vs
https://bloomington.in.gov/data


In any case, that's all I can remember.  I don't anticipate working to fix our validation problems with the federal data.gov anytime soon, as I'm working on several other larger projects.

Again, it's fair to kill off this PR, if the changes don't seem like they fit with where the project is now, or where it's going.

**Comment by btylerburton** [comment]
Closing this PR as outdated and OBE.

**Pull request closed without merging**
