### PR TITLE
add order_by so that active package wins

### PR DESCRIPTION
**Pull request by FuhuXia**
For https://github.com/GSA/data.gov/issues/2989.

Adding a `sort_by` and let the active package, if any,  be the last one in the `existing_datasets`.

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
I'm assuming you tested this @FuhuXia?

**Comment by FuhuXia** [comment]
> I'm assuming you tested this @FuhuXia?

Yes, tested on my local with prod db. we can also manually cf push this to staging.

**Comment by robert-bryson** [comment]
Wait, does manual `cf push`ing work any more?

I had thought we are supposed to do something like [this](https://github.com/GSA/catalog.data.gov/commit/05fde574f95e9b20931c5e5bf0bdc2f131ca96fc)? Or is this a different case (do you need the prod data to test?)?

**Comment by FuhuXia** [comment]
> Wait, does manual `cf push`ing work any more?
> 
> I had thought we are supposed to do something like [this](https://github.com/GSA/catalog.data.gov/commit/05fde574f95e9b20931c5e5bf0bdc2f131ca96fc)? Or is this a different case (do you need the prod data to test?)?

Not sure about this question. Manual CF push always works on dev/staging. Not recommended on dev but from time to time we find an excuse to do it. But for staging it is the only way to test something to staging without affecting prod.

**Comment by btylerburton** [comment]
Based on the comments on the original issue, should we focus on getting this https://github.com/GSA/data.gov/issues/3999 working instead? Or, do you think it's safe to include this order_by as a safety catch?

**Comment by FuhuXia** [comment]
> Based on the comments on the original issue, should we focus on getting this [GSA/data.gov#3999](https://github.com/GSA/data.gov/issues/3999) working instead? Or, do you think it's safe to include this order_by as a safety catch?

More than a safety catch. It is needed since purge will always runs behind, not real time. It is ok to have deleted packages staying in the system for a while. CKAN is designed that way. But when it is getting too much, like they are more than 2 years old or count for 30%+ of total count, we need to purge it.

**Review by nickumia-reisys — APPROVED** [review]
🦄

**Pull request merged**
